config/routes.rb
Noisebytes::Application.routes.draw do
  devise_for :accounts, :controllers => {:registrations => 'registrations', :profiles => 'profiles'}
  resources :index
  resources :profiles
  namespace :wepay do
    resources :authorize, :only => [:index]
    resources :ipn, :only => [:index]
  end
  namespace :purchase do
    resources :credits
    resource :cart, :has_many => :purchase_items
    resources :checkout, :only => [:index]
    resources :finalize, :only => [:index]
  end

  root :to => "index#index"

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :account
  validates_presence_of :account

  mount_uploader :avatar, AvatarUploader, :as => :avatar

  wepayable :wepay_auth_code

  def full_name
    "#{first_name} #{last_name}"
  end

  def location
    "#{city}, #{state}"
  end

  def avatar_url(type)
    return avatar.send(type).url if avatar.present?
    '/images/logo.png'
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_filter :authenticate_account!
  before_filter :merge_current_user_into_params, :only => ['create','update']
  # GET /profiles
  # GET /profiles.xml
  def index
    @profiles = Profile.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @profiles }
    end
  end

  # GET /profiles/1
  # GET /profiles/1.xml
  def show
    @profile = current_profile #Profile.find_by_account_id(current_account.id)

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @profile }
    end
  end

  # GET /profiles/new
  # GET /profiles/new.xml
  def new
    @profile = Profile.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @profile }
    end
  end

  # GET /profiles/1/edit
  def edit
    @profile = current_profile #Profile.find(params[:id])
    @account = current_account
  end

  # POST /profiles
  # POST /profiles.xml
  def create
    @profile = Profile.new(params[:profile])

    respond_to do |format|
      if @profile.save
        format.html { redirect_to(@profile, :notice => 'Profile was successfully created.') }
        format.xml  { render :xml => @profile, :status => :created, :location => @profile }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @profile.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /profiles/1
  # PUT /profiles/1.xml
  def update
    @profile = current_profile #Profile.find(params[:id])

    respond_to do |format|
      if @profile.update_attributes(params[:profile])
        format.html { redirect_to(@profile, :notice => 'Profile was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @profile.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.xml
  def destroy
    @profile = current_profile #Profile.find(params[:id])
    @profile.destroy

    respond_to do |format|
      format.html { redirect_to(profiles_url) }
      format.xml  { head :ok }
    end
  end

  def merge_current_user_into_params
    params[:profile].merge!(:account_id => current_account.id)
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_for(@profile, :html => { :multipart => true }) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div id="box_1" class="round dark-border taller">
  <%= image_tag @profile.avatar_url(:thumb), :class => "avatar slightly-round"  %>
  <div class="field">
    <div id="find_avatar" class="buttonize large shadow bottom-margin">Choose an Avatar</div><div id="selected_avatar"></div>
  </div>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
</div>
<div id="box_2" class="round dark-border taller">


  <div class="field">
    <%= f.label :bio %><br />
    <%= f.text_area :bio %>
  </div>
  <div class="field">
    <%= f.label :occupation %><br />
    <%= f.text_field :occupation %>
  </div>
  <div class="field">
    <%= f.label :company %><br />
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :website %><br />
    <%= f.text_field :website %>
  </div>
  <div class="actions">
    <%= f.submit :id => "profile_submit", :class => "shadow" %>
    <%= f.file_field :avatar, :id => "avatar_actual", :class => "see-through" %>
  </div>
<% end %>
</div>

<h2>Edit Your Login Credentials</h2>
<%= render :template => '/devise/registrations/edit'%>

<script type="text/javascript">
  $(document).ready(function(){
      var avatarActual = $('#avatar_actual');

      avatarActual.live('change', function(){
         var selectedAvatar = $('#selected_avatar');
         selectedAvatar.html("You've Selected: "+ avatarActual.val());
         selectedAvatar.show();
      });

      $('#find_avatar').click(function(){
            avatarActual.trigger('click');
      });
  });
</script>

app/views/profiles/edit.html.erb
<div id="box_container">
<h2>Edit your profile</h2>

<%= render 'form' %>

</div>

app/views/profiles/index.html.erb
<h1>Listing profiles</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Bio</th>
    <th>City</th>
    <th>State</th>
    <th>Occupation</th>
    <th>Company</th>
    <th>Website</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @profiles.each do |profile| %>
  <tr>
    <td><%= profile.first_name %></td>
    <td><%= profile.last_name %></td>
    <td><%= profile.bio %></td>
    <td><%= profile.city %></td>
    <td><%= profile.state %></td>
    <td><%= profile.occupation %></td>
    <td><%= profile.company %></td>
    <td><%= profile.website %></td>
    <td><%= link_to 'Show', profile %></td>
    <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
    <td><%= link_to 'Destroy', profile, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<div id="box_container">
<h2>Let the community get to know you better</h2>

<%= render 'form' %>

</div>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>
<div id="profile_container">
  <div id="profile_left">
    <p>
      <%= image_tag @profile.avatar_url(:thumb), :class => "avatar slightly-round" %>
    </p>

    <div id="blip_box">
      <h3>LAST <span class="text-light-blue">BLIP</span></h3>

      <p>
        <span class="text-light-yellow text-small add-line-height">20/04/2010</span>
      </p>

      <p class="add-10px-bottom-margin text-small add-line-height">
        <%= Faker::Lorem.paragraph[0..100] %>...
      </p>

      <p>
        <a href="#">
          <div class="read-more"></div>
        </a>
      </p>

      <p>
      <div class="vertical-navigation">
          <%= image_tag '/images/line-long.png', :class => "button-wrap-rule" %>
          <div class="navlet">
            <%= image_tag "/images/speaker.png" %>
            <a href="#">My Sound <span class='text-light-blue'>Library</span></a>
          </div>
          <%= image_tag '/images/line-long.png', :class => "button-wrap-rule" %>
          <div class="navlet">
            <%= image_tag "/images/profile-bubble.png" %>
            <a href="<%= edit_profile_path(@profile) %>">My <span class='text-light-blue'>Account</span></a>
          </div>
          <%= image_tag '/images/line-long.png', :class => "button-wrap-rule" %>
          <div class="navlet">
            <%= image_tag "/images/clip-board.png" %>
            <a href="#">My <span class="text-light-blue">Orders</span></a>
          </div>
          <%= image_tag '/images/line-long.png', :class => "button-wrap-rule" %>
      </div>
      </p>

    </div>
  </div>

  <div id="profile_center">
    <h3>Member Profile</h3>
    <h2 class="text-light-blue"><%= h @profile.full_name %></h2>

    <%= image_tag '/images/line-long.png', :class => "rule" %>

    <p>
      <span class="labelize dark-blue text-small">Member since:</span>
      <%= @profile.created_at.strftime("%B %Y") %>
    </p>

    <p>
      <span class="labelize text-small">Sounds Styles:</span>
      <%= h Faker::Lorem.words(20).to_s %>
    </p>

    <p>
      <span class="labelize dark-blue text-small">Occupation:</span>
      <%= h @profile.occupation %>
    </p>

    <p>
      <span class="labelize dark-blue text-small">Company:</span>
      <%= h @profile.company %>
    </p>

    <p>
      <span class="labelize dark-blue text-small">Website:</span>
      <%= h @profile.website %>
    </p>

    <p>
    <span class="labelize dark-blue text-small">Location:</span>
    <%= h @profile.location %>
    </p>

    <p>
      <span class="labelize dark-blue text-small">Biography:</span>
      <%= h @profile.bio %>
    </p>

    <%= image_tag '/images/line-long.png', :class => "rule" %>

    <h3 class="add-bottom-margin">Fans</h3>
    <table>
      <tr>
        <td><%= image_tag @profile.avatar_url(:tiny) %></td>
        <td><%= image_tag @profile.avatar_url(:tiny) %></td>
        <td><%= image_tag @profile.avatar_url(:tiny) %></td>
        <td><%= image_tag @profile.avatar_url(:tiny) %></td>
        <td><%= image_tag @profile.avatar_url(:tiny) %></td>
      </tr>
    </table>
  </div>

  <div id="profile_right">


  </div>
</div>