config/routes.rb
Noisebytes::Application.routes.draw do
  devise_for :accounts, :controllers => {:registrations => 'registrations', :profiles => 'profiles'}
  resources :index
  resources :profiles
  namespace :wepay do
    resources :authorize, :only => [:index]
    resources :ipn, :only => [:index]
  end
  namespace :purchase do
    resources :credits
    resource :cart, :has_many => :purchase_items
    resources :checkout, :only => [:index]
    resources :finalize, :only => [:index]
  end

  root :to => "index#index"

end

app/controllers/purchase/carts_controller.rb
class Purchase::CartsController < Purchase::PurchaseController
  before_filter :authenticate_account!
  before_filter :init_cart

  def show
  end

  def update
    product = Product.find(params[:product])
    @cart.add_product product, params[:qnty].to_i
    redirect_to :action => 'show'
  end

  def delete
    product = Product.find(params[:product])
    @cart.remove_product product, params[:qnty].to_i
    redirect_to :action => 'show'
  end

  private
  def init_cart
    @cart = current_account.cart
  end
end

app/controllers/purchase/checkout_controller.rb
class Purchase::CheckoutController < Purchase::PurchaseController
  before_filter :authenticate_account!

  def index
    if current_profile.has_wepay_auth_code?
      if wepay_access_token_exists?

        cart = current_account.cart
        tx_id = cart.init_transaction

        checkout_params = {
            :amount => cart.grand_total,
            :short_description => cart.short_description,
            :long_description => cart.long_description,
            :callback_uri => purchase_finalize_index_url(:txID => tx_id)
        }

        init_checkout_and_send_user_to_wepay checkout_params
      else
        initialize_wepay_access_token(current_profile.wepay_auth_code)
      end
    else
      redirect_to_wepay_for_auth
    end
  end
end

app/controllers/purchase/credits_controller.rb
class Purchase::CreditsController < Purchase::PurchaseController
  before_filter :authenticate_account!

  def index
    @credit_tiers = Product.credit_tiers
    @cart = current_account.shopping_cart
  end
end

app/controllers/purchase/finalize_controller.rb
class Purchase::FinalizeController < ApplicationController
  def index

  end
end

app/controllers/purchase/purchase_controller.rb
class Purchase::PurchaseController < ApplicationController
  include WepayRails::Payments
end

app/views/purchase/credits/index.html.haml
%h2.add-10px-bottom-margin Purchase Credits
%p
  In order to download sounds, you'll need to buy some credits. Please choose one of the price tiers below:
#credit_tiers
  - @credit_tiers.each do |tier|
    .tier
      %h4.add-10px-bottom-margin
        = tier.name
      %p
        = tier.description
      %p
        = cents_to_currency tier.price
      %p
        = form_for([:purchase, @cart], :url => purchase_cart_path) do |f|
          = hidden_field_tag 'product', tier.id
          = hidden_field_tag 'qnty', 1
          = submit_tag "Add to Cart",{:class => "shadow"}